"""initial schema

Revision ID: 328674a34f67
Revises: 
Create Date: 2026-05-05 18:11:48.506612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328674a34f67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sefirot',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('pilar', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('actividades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('serie_id', sa.String(length=36), nullable=True),
    sa.Column('rrule', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_serie_id'), 'actividades', ['serie_id'], unique=False)
    op.create_table('preguntas_sefirot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sefira_id', sa.String(length=50), nullable=False),
    sa.Column('texto_pregunta', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sefira_id'], ['sefirot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_diario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('sefira_id', sa.String(length=50), nullable=True),
    sa.Column('reflexion_texto', sa.Text(), nullable=False),
    sa.Column('puntuacion_usuario', sa.Integer(), nullable=True),
    sa.Column('puntuacion_ia', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sefira_id'], ['sefirot.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades_sefirot',
    sa.Column('actividad_id', sa.String(length=36), nullable=False),
    sa.Column('sefira_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sefira_id'], ['sefirot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actividad_id', 'sefira_id')
    )
    op.create_table('respuestas_preguntas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('pregunta_id', sa.String(length=36), nullable=False),
    sa.Column('respuesta_texto', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_sefirot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_preguntas')
    op.drop_table('actividades_sefirot')
    op.drop_table('registros_diario')
    op.drop_table('preguntas_sefirot')
    op.drop_index(op.f('ix_actividades_serie_id'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('sefirot')
    # ### end Alembic commands ###
