"""add gcal sync columns

Revision ID: e7470743e40a
Revises: 2c0d255f7492
Create Date: 2026-05-14 19:29:32.485645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7470743e40a'
down_revision: Union[str, Sequence[str], None] = '2c0d255f7492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('gcal_event_id', sa.String(length=255), nullable=True))
    op.add_column('actividades', sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=False))
    op.create_index(op.f('ix_actividades_gcal_event_id'), 'actividades', ['gcal_event_id'], unique=False)
    op.add_column('usuarios', sa.Column('google_refresh_token_enc', sa.Text(), nullable=True))
    op.add_column('usuarios', sa.Column('google_calendar_id', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('gcal_sync_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'gcal_sync_enabled')
    op.drop_column('usuarios', 'google_calendar_id')
    op.drop_column('usuarios', 'google_refresh_token_enc')
    op.drop_index(op.f('ix_actividades_gcal_event_id'), table_name='actividades')
    op.drop_column('actividades', 'sync_status')
    op.drop_column('actividades', 'gcal_event_id')
    # ### end Alembic commands ###
